
package zhong.webservice.clinet1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "UserWebService", targetNamespace = "www.zhong.webservice.demo", wsdlLocation = "http://localhost:8080/ws/userWebService?wsdl")
public class UserWebService_Service
    extends Service
{

    private final static URL USERWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(zhong.webservice.clinet1.UserWebService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = zhong.webservice.clinet1.UserWebService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/ws/userWebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/ws/userWebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        USERWEBSERVICE_WSDL_LOCATION = url;
    }

    public UserWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserWebService_Service() {
        super(USERWEBSERVICE_WSDL_LOCATION, new QName("www.zhong.webservice.demo", "UserWebService"));
    }

    /**
     * 
     * @return
     *     returns UserWebService
     */
    @WebEndpoint(name = "UserWebServiceImplPort")
    public UserWebService getUserWebServiceImplPort() {
        return super.getPort(new QName("www.zhong.webservice.demo", "UserWebServiceImplPort"), UserWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserWebService
     */
    @WebEndpoint(name = "UserWebServiceImplPort")
    public UserWebService getUserWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("www.zhong.webservice.demo", "UserWebServiceImplPort"), UserWebService.class, features);
    }

}
