
package zhong.webservice.clinet1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UserWebService", targetNamespace = "www.zhong.webservice.demo")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserWebService {


    /**
     * 
     * @param age
     * @param name
     */
    @WebMethod
    @RequestWrapper(localName = "createUser", targetNamespace = "www.zhong.webservice.demo", className = "zhong.webservice.clinet1.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "www.zhong.webservice.demo", className = "zhong.webservice.clinet1.CreateUserResponse")
    public void createUser(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "age", targetNamespace = "")
        Integer age);

    /**
     * 
     * @param userId
     * @return
     *     returns zhong.webservice.clinet1.User
     */
    @WebMethod
    @WebResult(name = "User", targetNamespace = "")
    @RequestWrapper(localName = "getUserByUserId", targetNamespace = "www.zhong.webservice.demo", className = "zhong.webservice.clinet1.GetUserByUserId")
    @ResponseWrapper(localName = "getUserByUserIdResponse", targetNamespace = "www.zhong.webservice.demo", className = "zhong.webservice.clinet1.GetUserByUserIdResponse")
    public User getUserByUserId(
        @WebParam(name = "userId", targetNamespace = "")
        Integer userId);

}
