
package zhong.webservice.clinet;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CoofansWebServiceService", targetNamespace = "http://service.docking.module.imall.iloosen.com/", wsdlLocation = "http://localhost:8080/ws/coofansWebService?wsdl")
public class CoofansWebServiceService
    extends Service
{

    private final static URL COOFANSWEBSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(zhong.webservice.clinet.CoofansWebServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = zhong.webservice.clinet.CoofansWebServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/ws/coofansWebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/ws/coofansWebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        COOFANSWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public CoofansWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CoofansWebServiceService() {
        super(COOFANSWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://service.docking.module.imall.iloosen.com/", "CoofansWebServiceService"));
    }

    /**
     * 
     * @return
     *     returns ICoofansWebService
     */
    @WebEndpoint(name = "CoofansWebServicePort")
    public ICoofansWebService getCoofansWebServicePort() {
        return super.getPort(new QName("http://service.docking.module.imall.iloosen.com/", "CoofansWebServicePort"), ICoofansWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICoofansWebService
     */
    @WebEndpoint(name = "CoofansWebServicePort")
    public ICoofansWebService getCoofansWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.docking.module.imall.iloosen.com/", "CoofansWebServicePort"), ICoofansWebService.class, features);
    }

}
